[package]
name = "mauskit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
mausbox-rs = { version = "0.1.0", path = "../mausbox-rs" }
plotters = "0.3.7"
